"$schema" = 'https://starship.rs/config-schema.json'
# https://starship.rs/config/

add_newline = false
format = '$all'
command_timeout = 1_000_000

[hostname]
format = "[  $ssh_symbol$hostname]($style) "
ssh_symbol = "\\(ssh\\) "
ssh_only = false
style = "green"

[nodejs]
format = "\\([$symbol($version)]($style)\\) "
version_format = "v${major}"

# [git_branch]
# format = "[$symbol$branch(:$remote_branch)]($style) "
# symbol = " "
# style = "blue"

[cmd_duration]
min_time = 120_000 # only show if it takes more than 120s (2min)
show_notifications = false
# min_time_to_notify = 1_000 # only notify if it takes more than 60s

[shell]
disabled = false
format = "[$indicator]($style)"
style = "yellow"
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
